spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8085
